
export function generateRoom(adjIndex, nounIndex) {
    const adj = adjectives[adjIndex];
    const nou = nouns[nounIndex];
    const adjLow = adj.charAt(0).toLowerCase() + adj.slice(1);

    return (adjLow + nou).toString()
}

const nouns = [
    "Park",
    "Forest",
    "City",
    "Beach",
    "Mountain",
    "Lake",
    "Village",
    "Island",
    "Desert",
    "Cave",
    "Castle",
    "Harbor",
    "Glacier",
    "Meadow",
    "Canyon",
    "Stadium",
    "Library",
    "Cafe",
    "Museum",
    "Market",
    "Farm",
    "Zoo",
    "School",
    "Church",
    "Temple",
    "Mosque",
    "Theater",
    "Stadium",
    "Hotel",
    "Airport",
    "Restaurant",
    "Bar",
    "Spa",
    "Hospital",
    "University",
    "Office",
    "Mall",
    "Courthouse",
    "Palace",
    "Mansion",
    "Cinema",
    "Cemetery",
    "Aquarium",
    "Observatory",
    "Observatory",
    "Factory",
    "Campsite",
    "Marina",
    "Tower",
    "Plaza"
]

const adjectives = [
    "Serene",
    "Bustling",
    "Picturesque",
    "Vibrant",
    "Tranquil",
    "Lively",
    "Historic",
    "Charming",
    "Idyllic",
    "Majestic",
    "Quaint",
    "Urban",
    "Rural",
    "Scenic",
    "Cosmopolitan",
    "Pristine",
    "Enchanting",
    "Atmospheric",
    "Sprawling",
    "Secluded",
    "Inviting",
    "Remote",
    "Sleek",
    "Modern",
    "Ancient",
    "Enigmatic",
    "Colorful",
    "Rustic",
    "Dynamic",
    "Fascinating",
    "Exotic",
    "Captivating",
    "Hidden",
    "Sophisticated",
    "Welcoming",
    "Coastal",
    "Vibrant",
    "Industrial",
    "Hilly",
    "Expansive",
    "Tranquil",
    "Bustling",
    "Remote",
    "Polished",
    "Historic",
    "Suburban",
    "Untamed",
    "Contemporary",
    "Windswept",
    "Peaceful",
]