services:
  webapp:
    build:
      context: .
      dockerfile: ./docker/webapp/Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
